import { Generated, Selectable } from 'kysely'

interface SongTable {
  // Columns that are generated by the database should be marked
  // using the `Generated` type. This way they are automatically
  // made optional in inserts and updates.
  id: Generated<number>

  artist_name: string
  track_name: string
  popularity: number
  year: number
  genre: string
  danceability: number
  energy: number
  key: number
  loudness: number
  speechiness: number
  acousticness: number
  liveness: number
  tempo: number
  duration_ms: number
  time_signature: number
}

export type Song = Selectable<SongTable>

// Keys of this interface are table names.
export interface Database {
  song: SongTable
}
